# Generated by Django 4.1 on 2022-08-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_booktour_tag_tour_customers_bill_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
