# Generated by Django 4.1 on 2022-09-05 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action', to='travel.tour'),
        ),
    ]
